### PR TITLE
Fix TeamGraph not loading on first login (and login following logout)

### LINKED ISSUE #2: Re-render graph on login followed by logout
Otherwise the previous user's graph state is shown instead of starting from a clean state, which isn't ideal.

### LINKED ISSUE #19: Graph doesn't render on first load
Or is that only first login? Need to investigate.

### PR DESCRIPTION
**Pull request by spinningarrow**
- Modified the way state is set and cleared - all state is cleared on
  Logout (rather than just the current user) and a separate method sets
  the state on Login (or if the user is already logged in from a previous)
  session
- Moved TeamGraph's init() and update() methods to componentDidMount()
  because we need the DOM element that render() creates before init() is
  called

This will fix #19 and will also fix #2.

Need @xevenheaven's :eyes: on this!

### CODE REVIEW

File: app/components/KudosApp.js [hunk 1]
```diff
@@ -1,13 +1,13 @@
...
-var React = require('react');
-var CurrentUserBox = require('./CurrentUserBox');
-var LoginForm = require('./LoginForm');
-var KudosBox = require('./KudosBox');
-var TeamGraph = require('./TeamGraph');
+let React = require('react');
+let CurrentUserBox = require('./CurrentUserBox');
+let LoginForm = require('./LoginForm');
+let KudosBox = require('./KudosBox');
+let TeamGraph = require('./TeamGraph');
```
Comment (xevenheaven) [inline app/components/KudosApp.js:8]: Nice! Liking the `let`s!
